export const state = {
    canvas: {
        width: 0,
        height: 0,
        bgColor: '#ffffff',
        zoom: 1,
        panX: 0,
        panY: 0,
        spaceHeld: false,
        pinching: false,
    },
    tool: {
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
        fontFamily: 'Comic Neue',
        fontSize: 32,
        color: '#000000',
        strokeWeight: 0,
        spacing: 1.0,
        continueFromLast: true,
        mode: 'paint',
        eraserRadius: 20,
    },
    painting: {
        isActive: false,
        charIndex: 0,
        pathPoints: [],
        smoothedAngle: 0,
        lastPlacedPos: null,
    },
    layers: {
        items: [],
        activeIndex: 0,
        maxLayers: 10,
        nextId: 0,
    },
    liveChars: [],
    settings: {
        locale: localStorage.getItem('ascii-paint-locale') || 'pt-BR',
    },
    colorHistory: {
        colors: [],
        maxColors: 12,
    },
    pressure: {
        penDetected: false,
        enabled: false,
        minMultiplier: 0.5,
        maxMultiplier: 2.0,
    },
};
